/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supported chains
         * @description Returns all chains OTI can score, with their internal chain IDs.
         */
        get: operations["getChains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/score/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Score a wallet (GET)
         * @description Computes or returns a cached trust score for the given wallet address
         *     on the specified chain. If the wallet is on the compromised denylist,
         *     returns a compromised response with `score: null` and no 4xx error.
         *
         *     Results are cached in memory. The first call fetches live on-chain data;
         *     subsequent calls for the same address+chain return `cached: true`.
         */
        get: operations["getScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score a wallet (POST)
         * @description Alternative to `GET /score/{address}`. Accepts `address` and `chain`
         *     in the request body instead of path and query parameters. Behaviour is
         *     identical — same caching, same compromised-wallet check, same response
         *     shapes.
         */
        post: operations["postScore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/score/{address}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get score history for a wallet
         * @description Returns the in-memory score history for the given wallet address and
         *     chain. History is populated each time a score is computed during the
         *     current server process lifetime — it is not persisted across restarts.
         */
        get: operations["getScoreHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/compromised": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List flagged wallets
         * @description Returns the compromised wallet denylist. Optionally filter by
         *     `chain_family` or `address` (case-insensitive partial match).
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        get: operations["listCompromisedWallets"];
        put?: never;
        /**
         * Flag a wallet as compromised
         * @description Adds a wallet address to the compromised denylist. Any subsequent score
         *     request for this address+chain_family will return `compromised: true`
         *     without computing a score.
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        post: operations["flagCompromisedWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/compromised/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a wallet from the denylist
         * @description Permanently removes a wallet entry from the compromised denylist by its
         *     UUID. The wallet will no longer be blocked from scoring.
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        delete: operations["deleteCompromisedWallet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List issued API keys
         * @description Returns all issued API keys. The raw key is never returned — only the
         *     last 4 characters (`last4`) are included.
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        get: operations["listApiKeys"];
        put?: never;
        /**
         * Issue a new API key
         * @description Creates a new API key for a wallet address under the given plan.
         *     The raw key (`api_key`) is returned **only on creation** — it cannot
         *     be retrieved again. Store it securely immediately.
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        post: operations["issueApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API key
         * @description Permanently deletes an API key by its UUID. Any request using this key
         *     will immediately receive `401 Invalid API key`.
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        /**
         * Update an API key's plan or expiry
         * @description Updates the `plan` and/or `expires_at` on an existing key. At least
         *     one field must be provided.
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        patch: operations["updateApiKey"];
        trace?: never;
    };
    "/admin/plan-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all plan tiers
         * @description Returns all four plan tiers: `anonymous`, `free`, `pro`, `enterprise`.
         *     `daily_limit: null` means unlimited.
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        get: operations["listPlanConfigs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/plan-configs/{plan_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a plan's daily limit or description
         * @description Live-updates a plan tier's `daily_limit` (pass `null` for unlimited)
         *     and/or `description`. Changes take effect immediately on the next
         *     request — no restart required. At least one field must be provided.
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        patch: operations["updatePlanConfig"];
        trace?: never;
    };
    "/admin/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily usage data
         * @description Returns daily request counts per key or anonymous IP. Optionally filter
         *     by `date` (YYYY-MM-DD) and/or `key_ref`.
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard summary statistics
         * @description Returns a high-level summary: total issued keys, total compromised
         *     wallets on the denylist, today's request count, and today's requests
         *     broken down by plan tier.
         *
         *     **Internal use only — no authentication required. Network-restricted in production.**
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Supported blockchain identifier
         * @default ethereum
         * @enum {string}
         */
        Chain: "ethereum" | "bsc" | "polygon" | "arbitrum" | "optimism" | "base" | "avalanche" | "fantom" | "linea" | "zksync" | "ton" | "solana" | "sui" | "bitcoin" | "tron";
        SignalBreakdown: {
            /** @description Score component derived from how long the wallet has been active */
            walletAge: number;
            /** @description Score component derived from number of transactions */
            transactionCount: number;
            /** @description Score component derived from token holding patterns */
            tokenHoldingBehavior: number;
            /** @description Score component derived from smart contract interaction history */
            smartContractInteractions: number;
            /** @description Score component derived from timing patterns between transactions */
            transactionTimingPatterns: number;
        };
        ScoreResponse: {
            /** @description Wallet address (lowercased for EVM) */
            address: string;
            chain: components["schemas"]["Chain"];
            /** @description Whether this result was served from in-memory cache */
            cached: boolean;
            /**
             * @description Always false on a normal scored response
             * @enum {boolean}
             */
            compromised: false;
            /** @description Overall trust score */
            score: number;
            signals: components["schemas"]["SignalBreakdown"];
        };
        CompromisedScoreResponse: {
            /** @description Wallet address */
            address: string;
            chain: components["schemas"]["Chain"];
            /**
             * @description Always true on a compromised response
             * @enum {boolean}
             */
            compromised: true;
            /** @description Human-readable reason the wallet was flagged */
            reason: string;
            /**
             * Format: date-time
             * @description UTC timestamp when the wallet was flagged
             */
            reported_at: string;
            /**
             * @description Always null for compromised wallets
             * @enum {unknown|null}
             */
            score: null;
        };
        ScoreRequest: {
            /** @description Wallet address */
            address: string;
            chain?: components["schemas"]["Chain"];
        };
        HistoryEntry: {
            score: number;
            signals: components["schemas"]["SignalBreakdown"];
        };
        HistoryResponse: {
            address: string;
            chain: components["schemas"]["Chain"];
            /** @description Number of history entries */
            count: number;
            history: components["schemas"]["HistoryEntry"][];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ChainsResponse: {
            count: number;
            chains: {
                name: components["schemas"]["Chain"];
                /** @description Internal chain identifier (non-EVM chains use a fixed negative value) */
                chainId: number;
            }[];
        };
        FlagCompromisedRequest: {
            /** @description Wallet address to flag */
            address: string;
            chain: components["schemas"]["Chain"];
            /** @description Human-readable reason for flagging */
            reason: string;
        };
        CompromisedWallet: {
            /** Format: uuid */
            id: string;
            address: string;
            /**
             * @description Chain family the entry applies to. All EVM chains share `evm`, so flagging on any EVM chain blocks the address on all EVM chains.
             * @enum {string}
             */
            chain_family: "evm" | "ton" | "solana" | "sui" | "bitcoin" | "tron";
            reason: string;
            /** Format: date-time */
            reported_at: string;
        };
        IssueKeyRequest: {
            /** @description Wallet address of the key owner */
            owner_address: string;
            /**
             * @description Plan tier to assign to this key
             * @enum {string}
             */
            plan: "free" | "pro" | "enterprise";
            /**
             * Format: date-time
             * @description Optional expiry timestamp. Omit or pass null for no expiry.
             */
            expires_at?: string | null;
        };
        /** @description Returned only on key creation. This is the sole response that contains the full raw API key — store it securely, it cannot be retrieved again. */
        ApiKeyCreated: {
            /** Format: uuid */
            id: string;
            /**
             * @description Full raw API key (format oti_<32 hex chars>). Shown once only.
             * @example oti_a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4
             */
            apiKey: string;
            plan: string;
            ownerAddress: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        /** @description API key summary. Raw key is never returned — only last4. */
        ApiKey: {
            /** Format: uuid */
            id: string;
            owner_address: string;
            plan: string;
            /**
             * @description Last 4 characters of the raw API key
             * @example 3d4e
             */
            last4: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description At least one field must be provided. */
        PatchKeyRequest: {
            /** @enum {string} */
            plan?: "free" | "pro" | "enterprise";
            /** Format: date-time */
            expires_at?: string | null;
        };
        PlanConfig: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            plan_name: "anonymous" | "free" | "pro" | "enterprise";
            /** @description Max requests per UTC day. null means unlimited. */
            daily_limit: number | null;
            description: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description At least one field must be provided. */
        PatchPlanRequest: {
            /** @description New daily limit. Pass null to make the plan unlimited. */
            daily_limit?: number | null;
            description?: string;
        };
        UsageRow: {
            /** Format: uuid */
            id: string;
            /** @description API key (raw) for keyed requests, or `anon:<ip>` for anonymous requests. */
            key_ref: string;
            /**
             * Format: date
             * @description UTC date of the usage bucket (YYYY-MM-DD)
             */
            usage_date: string;
            req_count: number;
            /** @description Plan name derived from the key. `anonymous` for anon requests, `unknown` if key was deleted. */
            plan_name: string;
        };
        StatsResponse: {
            /** @description Total number of issued API keys */
            total_keys: number;
            /** @description Total number of wallets on the compromised denylist */
            total_compromised: number;
            /** @description Total requests made today (UTC) */
            today_requests: number;
            /** @description Today's requests broken down by plan tier, sorted by req_count desc */
            requests_by_plan: {
                plan_name: string;
                req_count: number;
            }[];
        };
        DeletedResponse: {
            /** @enum {boolean} */
            deleted: true;
            /** Format: uuid */
            id: string;
        };
        ErrorResponse: {
            error: string;
        };
        ErrorDetailResponse: {
            error: string;
            details: string[] | string;
        };
        DailyRateLimitResponse: {
            /** @enum {string} */
            error: "Daily rate limit exceeded";
            /** @description The plan's daily request limit */
            limit: number;
            /**
             * Format: date-time
             * @description UTC timestamp when the daily counter resets (midnight UTC)
             */
            reset: string;
        };
        IpRateLimitResponse: {
            /** @enum {string} */
            error: "Too many requests";
            /** @description Human-readable explanation of the IP burst limit */
            details: string;
        };
    };
    responses: {
        /** @description Invalid request parameters or body */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Invalid request",
                 *       "details": [
                 *         "Must be a valid Ethereum wallet address (0x followed by 40 hex characters)"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorDetailResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "No API key found with id \"3fa85f64-5717-4562-b3fc-2c963f66afa6\""
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Daily rate limit exceeded */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DailyRateLimitResponse"] | components["schemas"]["IpRateLimitResponse"];
            };
        };
    };
    parameters: {
        /** @description Wallet address. Format depends on chain: EVM `0x` + 40 hex chars; TON starts with `EQ` or `UQ`, 48 chars; Solana base58, 32–44 chars; Sui `0x` + 64 hex chars; Bitcoin Legacy `1…`, Script `3…`, SegWit `bc1q…`, or Taproot `bc1p…`; Tron starts with `T`, exactly 34 base58 chars. */
        AddressPath: string;
        /** @description Target chain. Defaults to `ethereum` when omitted. */
        ChainQuery: components["schemas"]["Chain"];
        /** @description UUID of the resource */
        IdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getChains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of supported chains */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainsResponse"];
                };
            };
        };
    };
    getScore: {
        parameters: {
            query?: {
                /** @description Target chain. Defaults to `ethereum` when omitted. */
                chain?: components["parameters"]["ChainQuery"];
            };
            header?: never;
            path: {
                /** @description Wallet address. Format depends on chain: EVM `0x` + 40 hex chars; TON starts with `EQ` or `UQ`, 48 chars; Solana base58, 32–44 chars; Sui `0x` + 64 hex chars; Bitcoin Legacy `1…`, Script `3…`, SegWit `bc1q…`, or Taproot `bc1p…`; Tron starts with `T`, exactly 34 base58 chars. */
                address: components["parameters"]["AddressPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Score result. Check the `compromised` field: if `true`, the wallet
             *     is on the denylist and `score` will be `null`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"] | components["schemas"]["CompromisedScoreResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Wallet not found or has no on-chain activity */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Ethereum wallet not found or has no activity"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            /** @description Failed to fetch on-chain data from the upstream provider */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Failed to fetch on-chain data",
                     *       "details": "Request timeout after 10000ms"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorDetailResponse"];
                };
            };
        };
    };
    postScore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "address": "0xd8da6bf26964af9d7eed9e03e53415d37aa96045",
                 *       "chain": "ethereum"
                 *     }
                 */
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Score result (same shape as GET /score/{address}) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"] | components["schemas"]["CompromisedScoreResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Wallet not found or has no on-chain activity */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            /** @description Failed to fetch on-chain data from the upstream provider */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetailResponse"];
                };
            };
        };
    };
    getScoreHistory: {
        parameters: {
            query?: {
                /** @description Target chain. Defaults to `ethereum` when omitted. */
                chain?: components["parameters"]["ChainQuery"];
            };
            header?: never;
            path: {
                /** @description Wallet address. Format depends on chain: EVM `0x` + 40 hex chars; TON starts with `EQ` or `UQ`, 48 chars; Solana base58, 32–44 chars; Sui `0x` + 64 hex chars; Bitcoin Legacy `1…`, Script `3…`, SegWit `bc1q…`, or Taproot `bc1p…`; Tron starts with `T`, exactly 34 base58 chars. */
                address: components["parameters"]["AddressPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Score history for the wallet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "address": "0xd8da6bf26964af9d7eed9e03e53415d37aa96045",
                     *       "chain": "ethereum",
                     *       "count": 2,
                     *       "history": [
                     *         {
                     *           "score": 78,
                     *           "signals": {
                     *             "walletAge": 85,
                     *             "transactionCount": 90,
                     *             "tokenHoldingBehavior": 70,
                     *             "smartContractInteractions": 65,
                     *             "transactionTimingPatterns": 60
                     *           }
                     *         },
                     *         {
                     *           "score": 76,
                     *           "signals": {
                     *             "walletAge": 85,
                     *             "transactionCount": 88,
                     *             "tokenHoldingBehavior": 68,
                     *             "smartContractInteractions": 63,
                     *             "transactionTimingPatterns": 56
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    listCompromisedWallets: {
        parameters: {
            query?: {
                /** @description Filter by chain family */
                chain_family?: "evm" | "ton" | "solana" | "sui" | "bitcoin" | "tron";
                /** @description Filter by address (case-insensitive partial match) */
                address?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of compromised wallets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompromisedWallet"][];
                };
            };
        };
    };
    flagCompromisedWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "address": "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
                 *       "chain": "ethereum",
                 *       "reason": "Flagged by Chainalysis — linked to Lazarus Group"
                 *     }
                 */
                "application/json": components["schemas"]["FlagCompromisedRequest"];
            };
        };
        responses: {
            /** @description Wallet flagged successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompromisedWallet"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Wallet is already flagged for this chain family */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Wallet already flagged for this chain family"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteCompromisedWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the resource */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet removed from denylist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "deleted": true,
                     *       "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                     *     }
                     */
                    "application/json": components["schemas"]["DeletedResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listApiKeys: {
        parameters: {
            query?: {
                /** @description Filter by plan tier */
                plan?: "free" | "pro" | "enterprise";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of API keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"][];
                };
            };
        };
    };
    issueApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "owner_address": "0xd8da6bf26964af9d7eed9e03e53415d37aa96045",
                 *       "plan": "free",
                 *       "expires_at": null
                 *     }
                 */
                "application/json": components["schemas"]["IssueKeyRequest"];
            };
        };
        responses: {
            /**
             * @description API key created. The `apiKey` field contains the full raw key —
             *     this is the **only** response that ever returns the raw value.
             */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the resource */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "deleted": true,
                     *       "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                     *     }
                     */
                    "application/json": components["schemas"]["DeletedResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the resource */
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "plan": "pro",
                 *       "expires_at": "2026-12-31T23:59:59.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["PatchKeyRequest"];
            };
        };
        responses: {
            /** @description Updated key (last4 only — raw key is never returned) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listPlanConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All plan configurations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "1fa85f64-5717-4562-b3fc-2c963f66afa1",
                     *         "plan_name": "anonymous",
                     *         "daily_limit": 3,
                     *         "description": "No API key — dashboard visitors",
                     *         "updated_at": "2024-01-01T00:00:00.000Z"
                     *       },
                     *       {
                     *         "id": "2fa85f64-5717-4562-b3fc-2c963f66afa2",
                     *         "plan_name": "free",
                     *         "daily_limit": 1000,
                     *         "description": "Manually issued developer key",
                     *         "updated_at": "2024-01-01T00:00:00.000Z"
                     *       },
                     *       {
                     *         "id": "3fa85f64-5717-4562-b3fc-2c963f66afa3",
                     *         "plan_name": "pro",
                     *         "daily_limit": 100000,
                     *         "description": "Paid developer key",
                     *         "updated_at": "2024-01-01T00:00:00.000Z"
                     *       },
                     *       {
                     *         "id": "4fa85f64-5717-4562-b3fc-2c963f66afa4",
                     *         "plan_name": "enterprise",
                     *         "daily_limit": null,
                     *         "description": "Unlimited access",
                     *         "updated_at": "2024-01-01T00:00:00.000Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["PlanConfig"][];
                };
            };
        };
    };
    updatePlanConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Name of the plan tier to update */
                plan_name: "anonymous" | "free" | "pro" | "enterprise";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "daily_limit": 5000
                 *     }
                 */
                "application/json": components["schemas"]["PatchPlanRequest"];
            };
        };
        responses: {
            /** @description Updated plan configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanConfig"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getUsage: {
        parameters: {
            query?: {
                /** @description Filter to a specific UTC date (YYYY-MM-DD) */
                date?: string;
                /** @description Filter by key reference. For keyed requests this is the raw API key; for anonymous requests it is the string `anon:<ip>`. */
                key_ref?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage rows ordered by date desc, req_count desc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *         "key_ref": "anon:203.0.113.42",
                     *         "usage_date": "2025-07-03",
                     *         "req_count": 3,
                     *         "plan_name": "anonymous"
                     *       },
                     *       {
                     *         "id": "4fa85f64-5717-4562-b3fc-2c963f66afa7",
                     *         "key_ref": "oti_abc123",
                     *         "usage_date": "2025-07-03",
                     *         "req_count": 142,
                     *         "plan_name": "free"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["UsageRow"][];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "total_keys": 48,
                     *       "total_compromised": 7,
                     *       "today_requests": 2341,
                     *       "requests_by_plan": [
                     *         {
                     *           "plan_name": "free",
                     *           "req_count": 1850
                     *         },
                     *         {
                     *           "plan_name": "anonymous",
                     *           "req_count": 430
                     *         },
                     *         {
                     *           "plan_name": "pro",
                     *           "req_count": 61
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
}
